apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: driver-api
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/override: do-not-preserve-host
    konghq.com/plugins: oidc-driver,rl-by-header,prometheus-driver
spec:
  rules:
    - http:
        paths:
          - path: /api/driver
            pathType: Prefix
            backend:
              service:
                name: driver
                port:
                  number: 80
