apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: driver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: driver
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 5
