apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    app: driver
    stack: echo
    interface: rest
    language: golang
  name: driver
spec:
  type: LoadBalancer
  selector:
    app: driver
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
