apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: driver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: k8s
    repoURL: https://github.com/maratonafullcyclesidartaoss/fullcycle-maratona-1-codelivery-part-6-driver-share.git
    targetRevision: HEAD
    kustomize:
  destination:
    namespace: driver
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

